/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type DefaultLocale = string;
export type DisplayName = string;
export type TenantId = string;
export type Tenants = DashboardTenant[];

export interface DashboardTenants {
  tenants: Tenants;
}
export interface DashboardTenant {
  default_locale: DefaultLocale;
  display_name: DisplayName;
  tenant_id: TenantId;
}
