/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type Count = number;
export type Examples = string[];
export type LastSeen = string;
export type Question = string;
export type Groups = QuestionGroup[];
export type PeriodEnd = string;
export type PeriodStart = string;
export type QuestionsWithoutAnswer = number;
export type TenantId = string;

export interface DashboardKnowledgeGaps {
  groups: Groups;
  period_end: PeriodEnd;
  period_start: PeriodStart;
  questions_without_answer: QuestionsWithoutAnswer;
  tenant_id: TenantId;
}
export interface QuestionGroup {
  count: Count;
  examples: Examples;
  last_seen: LastSeen;
  question: Question;
}
