/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type Now = string;
export type Overdue = number;
export type AgeSeconds = number;
export type CaseId = string;
export type ClaimedBy = string | null;
export type ConversationId = string;
export type CreatedAt = string;
export type HasPendingApproval = boolean;
export type Language = string | null;
export type Overdue1 = boolean;
export type Priority = string;
export type Reason = string;
export type RemainingSeconds = number;
export type SlaSeconds = number;
export type CaseStatus = "open" | "claimed" | "resolved" | "returned_to_agent";
export type Summary = string;
export type Rows = DashboardQueueRow[];
export type TenantId = string;

export interface DashboardQueue {
  now: Now;
  overdue: Overdue;
  rows: Rows;
  tenant_id: TenantId;
}
export interface DashboardQueueRow {
  age_seconds: AgeSeconds;
  case_id: CaseId;
  claimed_by: ClaimedBy;
  conversation_id: ConversationId;
  created_at: CreatedAt;
  has_pending_approval: HasPendingApproval;
  language: Language;
  overdue: Overdue1;
  priority: Priority;
  reason: Reason;
  remaining_seconds: RemainingSeconds;
  sla_seconds: SlaSeconds;
  status: CaseStatus;
  summary: Summary;
}
