/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type Change = number | null;
export type Previous = number | null;
export type Value = number | null;
export type OpenCases = number;
export type PeriodEnd = string;
export type PeriodStart = string;
export type PreviousEnd = string;
export type PreviousStart = string;
export type TenantId = string;

export interface DashboardOverview {
  automation_rate: DashboardKpi;
  conversations: DashboardKpi;
  escalation_rate: DashboardKpi;
  open_cases: OpenCases;
  p95_latency_ms: DashboardKpi;
  period_end: PeriodEnd;
  period_start: PeriodStart;
  previous_end: PreviousEnd;
  previous_start: PreviousStart;
  tenant_id: TenantId;
  unverified_results: DashboardKpi;
}
export interface DashboardKpi {
  change: Change;
  previous: Previous;
  value: Value;
}
