/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type CaseId = string;
export type ClaimedBy = string | null;
export type ConversationId = string;
export type CreatedAt = string;
export type Actor = string;
export type At = string;
export type Kind = string;
export type Note = string;
export type Events = CaseEvent[];
export type AiSuggestion = string | null;
export type AiSummary = string | null;
export type AiSummaryLocal = string | null;
export type AuditId = string | null;
export type Error = string | null;
export type ExecutionId = string | null;
export type History = string[];
export type ProposalId = string;
export type State = string;
export type Tool = string;
export type AttemptedActions = AttemptedAction[];
export type CustomerId = string | null;
export type Method = string | null;
export type Orders = string[];
export type PhoneMasked = string | null;
export type Verified = boolean;
export type Detail = string;
export type AuditId1 = string | null;
export type ErrorCode = string;
export type ExecutionId1 = string | null;
export type Message = string;
export type Source = string;
export type TraceId = string | null;
export type Failures = FailureRecord[];
export type Intents = string[];
/**
 * Language style of the customer message.
 */
export type Language = "en" | "ar" | "mixed" | "arabizi";
export type Capability = string;
export type ProposalId1 = string;
export type Reason = string;
export type Tool1 = string;
export type Citation = string;
export type Text = string;
export type PolicyQuotes = PolicyQuote[];
export type Priority = "urgent" | "high" | "normal" | "low";
export type PromptVersion = string | null;
/**
 * Why a conversation goes to a human. Each one has a priority and a suggested next step (later prompts).
 */
export type EscalationReason =
  | "customer_request"
  | "mandatory_risk"
  | "policy_denied"
  | "approval_required"
  | "repeated_tool_failure"
  | "unverified_result"
  | "no_evidence"
  | "dependency_unavailable"
  | "low_confidence"
  | "identity_failed"
  | "ownership_mismatch"
  | "high_frustration"
  | "capability_missing"
  | "unsupported";
export type Action = string;
export type Citations = string[];
export type Decision = "allow" | "deny" | "require_human";
export type ReasonCode = string;
export type RequestId = string;
export type RuleAnswers = PolicyRecord[];
export type SafetyFlags = string[];
export type Category = string;
export type Citation1 = string;
export type Resolution = string;
export type TicketId = string;
export type SimilarTickets = SimilarTicket[];
export type SuggestedNextStep = string;
export type Summary = string;
export type SummarySource = "template" | "ai";
export type TraceIds = string[];
export type Role = "customer" | "agent";
export type Text1 = string;
export type TraceId1 = string;
export type TurnIndex = number;
export type Transcript = TranscriptLine[];
export type CaseStatus = "open" | "claimed" | "resolved" | "returned_to_agent";
export type TenantId = string;
export type UpdatedAt = string;
export type ConversationId1 = string;
export type TenantId1 = string;
export type ActiveIntent = string | null;
export type ConversationId2 = string;
export type CustomerMessage = string;
/**
 * Every customer message ends in exactly one of these.
 */
export type Decision1 = "answer" | "clarify" | "verify_identity" | "confirm" | "execute" | "refuse" | "handoff";
export type DecisionReason = string;
export type Errors = string[];
export type Citation2 = string;
export type DocumentId = string;
export type Score = number;
export type Version = string;
export type Evidence = EvidenceRef[];
export type EvidenceEmptyReason = string | null;
export type Frustration = ("low" | "medium" | "high") | null;
export type HandoffCaseId = string | null;
export type Attempts = number;
export type CustomerId1 = string | null;
export type Method1 = string | null;
export type Verified1 = boolean;
export type Confidence = number;
export type Name = string;
export type Intents1 = IntentCandidate[];
export type Kind1 = "customer_turn" | "human_action";
export type KnowledgeAnswer = boolean;
export type LatencyMs = number;
export type NluMethod = ("rules" | "llm" | "rules_fallback") | null;
export type Allowed = boolean;
export type Reason1 = string | null;
export type Policy = PolicyRecord[];
export type ProposalId2 = string;
export type State1 = string;
export type Tool2 = string;
export type Proposals = ProposalRecord[];
export type RequestId1 = string;
export type ResponseCitations = string[];
export type ResponseText = string;
export type RiskCategories = string[];
export type Detail1 = string;
export type DurationMs = number;
export type Stage = string;
export type Status = string;
export type Steps = TraceStep[];
export type TenantId2 = string;
export type Actor1 = "customer" | "human";
export type ApprovalId = string | null;
export type AuditId2 = string | null;
export type ErrorCode1 = string | null;
export type LatencyMs1 = number;
export type OperationKind = "read" | "create" | "update" | "delete";
export type PolicyRequestId = string | null;
export type RequestId2 = string;
export type Status1 = "success" | "error";
export type Tool3 = string;
export type ToolCalls = ToolCallRecord[];
export type TraceId2 = string;
export type TurnIndex1 = number;
export type Traces = DecisionTrace[];
export type Transcript1 = TranscriptLine[];

export interface DashboardConversation {
  case: HandoffCase | null;
  conversation_id: ConversationId1;
  tenant_id: TenantId1;
  traces: Traces;
  transcript: Transcript1;
}
export interface HandoffCase {
  case_id: CaseId;
  claimed_by?: ClaimedBy;
  conversation_id: ConversationId;
  created_at: CreatedAt;
  events?: Events;
  package: HandoffPackage;
  pending_approval?: PendingApproval | null;
  status?: CaseStatus;
  tenant_id: TenantId;
  updated_at: UpdatedAt;
}
export interface CaseEvent {
  actor: Actor;
  at: At;
  kind: Kind;
  note?: Note;
}
/**
 * Everything a human needs, built from recorded facts so the customer never has to repeat anything.
 */
export interface HandoffPackage {
  ai_suggestion?: AiSuggestion;
  ai_summary?: AiSummary;
  ai_summary_local?: AiSummaryLocal;
  attempted_actions?: AttemptedActions;
  customer?: CustomerSnapshot;
  detail?: Detail;
  details?: Details;
  failures?: Failures;
  intents?: Intents;
  language?: Language | null;
  order_facts?: OrderFacts;
  pending_approval?: PendingApproval | null;
  policy_quotes?: PolicyQuotes;
  priority: Priority;
  prompt_version?: PromptVersion;
  reason: EscalationReason;
  rule_answers?: RuleAnswers;
  safety_flags?: SafetyFlags;
  similar_tickets?: SimilarTickets;
  suggested_next_step: SuggestedNextStep;
  summary: Summary;
  summary_source?: SummarySource;
  trace_ids?: TraceIds;
  transcript?: Transcript;
}
export interface AttemptedAction {
  arguments?: Arguments;
  audit_id?: AuditId;
  error?: Error;
  execution_id?: ExecutionId;
  history?: History;
  proposal_id: ProposalId;
  state: State;
  tool: Tool;
}
export interface Arguments {
  [k: string]: unknown;
}
export interface CustomerSnapshot {
  customer_id?: CustomerId;
  method?: Method;
  orders?: Orders;
  phone_masked?: PhoneMasked;
  verified?: Verified;
}
export interface Details {
  [k: string]: string;
}
/**
 * A tool or system failure seen in this conversation.
 */
export interface FailureRecord {
  audit_id?: AuditId1;
  error_code: ErrorCode;
  execution_id?: ExecutionId1;
  message?: Message;
  source: Source;
  trace_id?: TraceId;
}
export interface OrderFacts {
  [k: string]: unknown;
}
/**
 * An action that waits for a human to approve it.
 */
export interface PendingApproval {
  arguments?: Arguments1;
  capability: Capability;
  proposal_id: ProposalId1;
  reason?: Reason;
  tool: Tool1;
}
export interface Arguments1 {
  [k: string]: unknown;
}
/**
 * A policy passage quoted exactly as written, with its source.
 */
export interface PolicyQuote {
  citation: Citation;
  text: Text;
}
export interface PolicyRecord {
  action: Action;
  citations?: Citations;
  decision: Decision;
  reason_code: ReasonCode;
  request_id: RequestId;
}
/**
 * A past ticket that looks like this one, so staff can see how it was solved.
 */
export interface SimilarTicket {
  category: Category;
  citation: Citation1;
  resolution: Resolution;
  ticket_id: TicketId;
}
export interface TranscriptLine {
  role: Role;
  text: Text1;
  trace_id: TraceId1;
  turn_index: TurnIndex;
}
export interface DecisionTrace {
  active_intent?: ActiveIntent;
  conversation_id: ConversationId2;
  customer_message?: CustomerMessage;
  decision: Decision1;
  decision_reason?: DecisionReason;
  entities?: Entities;
  errors?: Errors;
  escalation_reason?: EscalationReason | null;
  evidence?: Evidence;
  evidence_empty_reason?: EvidenceEmptyReason;
  frustration?: Frustration;
  handoff_case_id?: HandoffCaseId;
  identity?: SessionIdentity;
  intents?: Intents1;
  kind?: Kind1;
  knowledge_answer?: KnowledgeAnswer;
  language?: Language | null;
  latency_ms?: LatencyMs;
  nlu_method?: NluMethod;
  permission?: PermissionRecord | null;
  policy?: Policy;
  proposals?: Proposals;
  request_id: RequestId1;
  response_citations?: ResponseCitations;
  response_text?: ResponseText;
  risk_categories?: RiskCategories;
  steps?: Steps;
  tenant_id: TenantId2;
  tool_calls?: ToolCalls;
  trace_id: TraceId2;
  turn_index: TurnIndex1;
  versions?: Versions;
}
export interface Entities {
  [k: string]: string;
}
export interface EvidenceRef {
  citation: Citation2;
  document_id: DocumentId;
  score: Score;
  version: Version;
}
/**
 * Has this customer proved who they are? Set only by the identity check, never from what the customer says.
 */
export interface SessionIdentity {
  attempts?: Attempts;
  customer_id?: CustomerId1;
  method?: Method1;
  verified?: Verified1;
}
export interface IntentCandidate {
  confidence: Confidence;
  name: Name;
}
export interface PermissionRecord {
  allowed: Allowed;
  reason?: Reason1;
}
export interface ProposalRecord {
  proposal_id: ProposalId2;
  state: State1;
  tool: Tool2;
}
export interface TraceStep {
  detail?: Detail1;
  duration_ms?: DurationMs;
  stage: Stage;
  status: Status;
}
export interface ToolCallRecord {
  actor?: Actor1;
  approval_id?: ApprovalId;
  arguments?: Arguments2;
  audit_id?: AuditId2;
  error_code?: ErrorCode1;
  latency_ms?: LatencyMs1;
  operation_kind: OperationKind;
  policy_request_id?: PolicyRequestId;
  request_id: RequestId2;
  status: Status1;
  tool: Tool3;
}
export interface Arguments2 {
  [k: string]: unknown;
}
export interface Versions {
  [k: string]: string;
}
