/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type Actions = number;
export type AvgLatencyMs = number;
export type CaseId = string | null;
export type CaseStatus = "open" | "claimed" | "resolved" | "returned_to_agent";
export type ConversationId = string;
export type EscalationReason = string | null;
export type FirstAt = string;
export type HasCase = boolean;
export type Intents = string[];
export type Language = string | null;
export type LastAt = string;
export type Outcome = string;
export type Problems = string[];
export type Turns = number;
export type Items = DashboardConversationRow[];
export type NextCursor = string | null;

export interface DashboardConversationPage {
  items: Items;
  next_cursor?: NextCursor;
}
export interface DashboardConversationRow {
  actions: Actions;
  avg_latency_ms: AvgLatencyMs;
  case_id: CaseId;
  case_status: CaseStatus | null;
  conversation_id: ConversationId;
  escalation_reason: EscalationReason;
  first_at: FirstAt;
  has_case: HasCase;
  intents: Intents;
  language: Language;
  last_at: LastAt;
  outcome: Outcome;
  problems: Problems;
  turns: Turns;
}
