/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type PeriodEnd = string;
export type PeriodStart = string;
export type TenantId = string;
export type Calls = number;
export type Failures = number;
export type P50Ms = number | null;
export type P95Ms = number | null;
export type Rate = number;
export type Tool = string;
export type Tools = DashboardToolRow[];

export interface DashboardTools {
  period_end: PeriodEnd;
  period_start: PeriodStart;
  tenant_id: TenantId;
  tools: Tools;
}
export interface DashboardToolRow {
  calls: Calls;
  errors: Errors;
  failures: Failures;
  p50_ms: P50Ms;
  p95_ms: P95Ms;
  rate: Rate;
  tool: Tool;
}
export interface Errors {
  [k: string]: number;
}
