/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type Citation = string;
export type DocumentId = string;
export type Language = string;
export type Section = string;
export type Text = string;
export type Version = string;

/**
 * A policy passage exactly as stored, for the evidence a decision stood on.
 */
export interface DashboardPassage {
  citation: Citation;
  document_id: DocumentId;
  language: Language;
  section: Section;
  text: Text;
  version: Version;
}
