/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type BucketStart = string;
export type Conversations = number;
export type ByReason = ReasonPoint[];
export type ClaimedCases = number;
export type Conversations1 = number;
export type OpenCases = number;
export type PeriodEnd = string;
export type PeriodStart = string;
export type TenantId = string;
export type Count = number;
export type Decision = string;
export type Rule = string;
export type TopRules = DashboardRuleCount[];

export interface DashboardEscalations {
  by_reason: ByReason;
  by_reason_total: ByReasonTotal;
  claimed_cases: ClaimedCases;
  conversations: Conversations1;
  open_cases: OpenCases;
  period_end: PeriodEnd;
  period_start: PeriodStart;
  tenant_id: TenantId;
  top_rules: TopRules;
}
export interface ReasonPoint {
  bucket_start: BucketStart;
  by_reason: ByReason1;
  conversations: Conversations;
  rates: Rates;
}
export interface ByReason1 {
  [k: string]: number;
}
export interface Rates {
  [k: string]: number;
}
export interface ByReasonTotal {
  [k: string]: number;
}
export interface DashboardRuleCount {
  count: Count;
  decision: Decision;
  rule: Rule;
}
