/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in
   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */

export type Bucket = "hour" | "day" | "week" | "month";
export type Metric = string;
export type PeriodEnd = string;
export type PeriodStart = string;
export type Points = {
  [k: string]: unknown;
}[];
export type TenantId = string;

export interface DashboardTimeseries {
  bucket: Bucket;
  metric: Metric;
  period_end: PeriodEnd;
  period_start: PeriodStart;
  points: Points;
  tenant_id: TenantId;
}
