// Generates TypeScript types from the JSON Schemas the Team B service exports (team_b/contracts/schemas).
//
//   node scripts/gen-types.mjs           write src/api/types/<Name>.ts for every Dashboard*.schema.json
//   node scripts/gen-types.mjs --check   fail (exit 1) if a committed file differs from what the schemas would give,
//                                        or a schema has no file, or a file has no schema: the build runs this, so the
//                                        dashboard can never be built against stale types.
//
// After changing a response model in team_b/src/team_b/api/dashboard.py run `python scripts/export_schemas.py` in
// team_b/ and then `npm run types` here.
import { compileFromFile } from "json-schema-to-typescript";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = resolve(here, "../../team_b/contracts/schemas");
const outDir = resolve(here, "../src/api/types");
const check = process.argv.includes("--check");

const banner =
  "/* GENERATED by scripts/gen-types.mjs from team_b/contracts/schemas. Do not edit: change the model in\n" +
  "   team_b/src/team_b/api/dashboard.py, run `python scripts/export_schemas.py` there and `npm run types` here. */";

const names = readdirSync(schemasDir)
  .filter((f) => /^Dashboard.*\.schema\.json$/.test(f))
  .map((f) => f.replace(".schema.json", ""))
  .sort();
if (names.length === 0) {
  console.error(`no Dashboard*.schema.json in ${schemasDir}`);
  process.exit(1);
}

const normalize = (text) => text.replace(/\r\n/g, "\n");
const problems = [];
mkdirSync(outDir, { recursive: true });

for (const name of names) {
  const generated = await compileFromFile(join(schemasDir, `${name}.schema.json`), {
    bannerComment: banner,
    additionalProperties: false,
    declareExternallyReferenced: true,
    format: true,
  });
  const target = join(outDir, `${name}.ts`);
  if (check) {
    const current = existsSync(target) ? normalize(readFileSync(target, "utf8")) : null;
    if (current !== normalize(generated)) problems.push(`${name}.ts is ${current === null ? "missing" : "out of date"}`);
  } else {
    writeFileSync(target, generated);
    console.log(`wrote src/api/types/${name}.ts`);
  }
}

const expected = new Set(names.map((n) => `${n}.ts`));
for (const file of readdirSync(outDir)) {
  if (file.endsWith(".ts") && !expected.has(file)) problems.push(`${file} has no schema (delete it)`);
}

if (check && problems.length > 0) {
  console.error("The generated types are stale:\n  " + problems.join("\n  ") + "\nRun `npm run types` and commit the result.");
  process.exit(1);
}
if (check) console.log(`types are up to date (${names.length} schemas)`);
